import React, { useMemo, useState } from 'react'
import Title from '../../components/admin/Title'

const ageRatingOptions = ['P', 'K', 'T13', 'T16', 'T18', 'C']
const movieStatusOptions = ['COMING_SOON', 'NOW_SHOWING', 'ENDED']
const movieGenreOptions = [
  'ACTION',
  'ADVENTURE',
  'ANIMATION',
  'COMEDY',
  'CRIME',
  'DRAMA',
  'FANTASY',
  'HORROR',
  'MYSTERY',
  'ROMANCE',
  'SCI_FI',
  'THRILLER',
]

const initialMovieForm = {
  movie_id: '',
  title: '',
  description: '',
  age_rating: '',
  release_date: '',
  status: '',
  genre: '',
  duration_minutes: '',
}

const AddMovie = () => {
  const [formData, setFormData] = useState(initialMovieForm)
  const [submittedMovie, setSubmittedMovie] = useState(null)

  const canSubmit = useMemo(() => {
    return (
      formData.title &&
      formData.description &&
      formData.age_rating &&
      formData.release_date &&
      formData.status &&
      formData.genre &&
      Number(formData.duration_minutes) > 0
    )
  }, [formData])

  const handleChange = (field, value) => {
    setFormData((prev) => ({ ...prev, [field]: value }))
  }

  const handleSubmit = (event) => {
    event.preventDefault()
    if (!canSubmit) return

    const now = new Date().toISOString()
    setSubmittedMovie({
      ...formData,
      movie_id: formData.movie_id || `generated-at-api`,
      created_at: now,
      updated_at: null,
      duration_minutes: Number(formData.duration_minutes),
    })
  }

  return (
    <div className='space-y-6'>
      <Title text1='Add' text2='Movie' />

      <div className='rounded-xl border border-primary/20 bg-primary/10 p-4 text-sm text-gray-300'>
        Static prototype form for `Movies` entity. No API call yet.
      </div>

      <form onSubmit={handleSubmit} className='grid grid-cols-1 lg:grid-cols-2 gap-4'>
        <div className='space-y-2'>
          <label className='text-sm text-gray-300'>movie_id (optional)</label>
          <input
            value={formData.movie_id}
            onChange={(e) => handleChange('movie_id', e.target.value)}
            placeholder='Auto-generated by backend if empty'
            className='w-full rounded-md bg-black/30 border border-white/15 px-3 py-2 outline-none'
          />
        </div>

        <div className='space-y-2'>
          <label className='text-sm text-gray-300'>title *</label>
          <input
            value={formData.title}
            onChange={(e) => handleChange('title', e.target.value)}
            className='w-full rounded-md bg-black/30 border border-white/15 px-3 py-2 outline-none'
            required
          />
        </div>

        <div className='space-y-2 lg:col-span-2'>
          <label className='text-sm text-gray-300'>description *</label>
          <textarea
            value={formData.description}
            onChange={(e) => handleChange('description', e.target.value)}
            rows={4}
            className='w-full rounded-md bg-black/30 border border-white/15 px-3 py-2 outline-none'
            required
          />
        </div>

        <div className='space-y-2'>
          <label className='text-sm text-gray-300'>age_rating *</label>
          <select
            value={formData.age_rating}
            onChange={(e) => handleChange('age_rating', e.target.value)}
            className='w-full rounded-md bg-black/30 border border-white/15 px-3 py-2 outline-none'
            required
          >
            <option value=''>Select age rating</option>
            {ageRatingOptions.map((item) => (
              <option key={item} value={item}>
                {item}
              </option>
            ))}
          </select>
        </div>

        <div className='space-y-2'>
          <label className='text-sm text-gray-300'>release_date *</label>
          <input
            type='date'
            value={formData.release_date}
            onChange={(e) => handleChange('release_date', e.target.value)}
            className='w-full rounded-md bg-black/30 border border-white/15 px-3 py-2 outline-none'
            required
          />
        </div>

        <div className='space-y-2'>
          <label className='text-sm text-gray-300'>status *</label>
          <select
            value={formData.status}
            onChange={(e) => handleChange('status', e.target.value)}
            className='w-full rounded-md bg-black/30 border border-white/15 px-3 py-2 outline-none'
            required
          >
            <option value=''>Select status</option>
            {movieStatusOptions.map((item) => (
              <option key={item} value={item}>
                {item}
              </option>
            ))}
          </select>
        </div>

        <div className='space-y-2'>
          <label className='text-sm text-gray-300'>genre *</label>
          <select
            value={formData.genre}
            onChange={(e) => handleChange('genre', e.target.value)}
            className='w-full rounded-md bg-black/30 border border-white/15 px-3 py-2 outline-none'
            required
          >
            <option value=''>Select genre</option>
            {movieGenreOptions.map((item) => (
              <option key={item} value={item}>
                {item}
              </option>
            ))}
          </select>
        </div>

        <div className='space-y-2'>
          <label className='text-sm text-gray-300'>duration_minutes *</label>
          <input
            type='number'
            min='1'
            value={formData.duration_minutes}
            onChange={(e) => handleChange('duration_minutes', e.target.value)}
            className='w-full rounded-md bg-black/30 border border-white/15 px-3 py-2 outline-none'
            required
          />
        </div>

        <div className='lg:col-span-2'>
          <button
            type='submit'
            disabled={!canSubmit}
            className='cursor-pointer px-4 py-2 rounded-md bg-primary text-black font-medium hover:opacity-90 transition-opacity duration-200 disabled:opacity-50 disabled:cursor-not-allowed'
          >
            Save Mock Movie
          </button>
        </div>
      </form>

      {submittedMovie && (
        <div className='rounded-xl border border-primary/20 bg-primary/10 p-4'>
          <p className='font-medium mb-3'>Mock payload preview</p>
          <pre className='text-xs whitespace-pre-wrap break-all bg-black/30 p-3 rounded-md border border-white/10'>
            {JSON.stringify(submittedMovie, null, 2)}
          </pre>
        </div>
      )}
    </div>
  )
}

export default AddMovie
