import React, { useMemo, useRef, useState } from 'react'
import Title from '../../components/admin/Title'
import { createMovie } from '../../lib/movieApi'

const ageRatingOptions = ['G', 'PG', 'PG13', 'R', 'NC17']
const movieStatusOptions = ['COMING_SOON', 'NOW_SHOWING', 'ENDED']
const movieGenreOptions = [
  'ACTION',
  'ADVENTURE',
  'ANIMATION',
  'COMEDY',
  'CRIME',
  'DRAMA',
  'FANTASY',
  'HORROR',
  'MYSTERY',
  'ROMANCE',
  'SCI_FI',
  'THRILLER',
]

const initialMovieForm = {
  movie_id: '',
  title: '',
  description: '',
  age_rating: '',
  release_date: '',
  status: '',
  genre: '',
  duration_minutes: '',
  trailerUrl: '',
}

const uploadToPresignedUrl = async (url, file) => {
  const response = await fetch(url, {
    method: 'PUT',
    headers: { 'Content-Type': file.type || 'image/jpeg' },
    body: file,
  })

  if (!response.ok) {
    throw new Error(`Upload failed: ${response.status} ${response.statusText}`)
  }
}

const AddMovie = () => {
  const [formData, setFormData] = useState(initialMovieForm)
  const [horizontalFile, setHorizontalFile] = useState(null)
  const [verticalFile, setVerticalFile] = useState(null)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [submitError, setSubmitError] = useState('')
  const [submitSuccess, setSubmitSuccess] = useState('')
  const [uploadStatus, setUploadStatus] = useState({ horizontal: '', vertical: '' })

  const horizontalInputRef = useRef(null)
  const verticalInputRef = useRef(null)

  const canSubmit = useMemo(() => {
    return (
      formData.title &&
      formData.description &&
      formData.age_rating &&
      formData.release_date &&
      formData.status &&
      formData.genre &&
      Number(formData.duration_minutes) > 0 &&
      formData.trailerUrl
    )
  }, [formData])

  const handleChange = (field, value) => {
    setFormData((prev) => ({ ...prev, [field]: value }))
  }

  const handleSubmit = async (event) => {
    event.preventDefault()

    if (!canSubmit || isSubmitting) return

    setSubmitError('')
    setSubmitSuccess('')
    setUploadStatus({ horizontal: '', vertical: '' })

    try {
      setIsSubmitting(true)

      const payload = {
        ...(formData.movie_id ? { movie_id: formData.movie_id } : {}),
        title: formData.title,
        description: formData.description,
        age_rating: formData.age_rating,
        release_date: formData.release_date,
        status: formData.status,
        genre: formData.genre,
        duration_minutes: Number(formData.duration_minutes),
        trailerUrl: formData.trailerUrl,
      }

      // Backend returns ImgUrlDto { horizontal: presignedPutUrl, vertical: presignedPutUrl }
      const imgUrls = await createMovie(payload)

      const uploadResults = { horizontal: '', vertical: '' }

      if (horizontalFile && imgUrls?.horizontal) {
        try {
          await uploadToPresignedUrl(imgUrls.horizontal, horizontalFile)
          uploadResults.horizontal = 'uploaded'
        } catch (err) {
          uploadResults.horizontal = `failed: ${err.message}`
        }
      } else if (!imgUrls?.horizontal) {
        uploadResults.horizontal = 'no url returned'
      } else {
        uploadResults.horizontal = 'skipped (no file selected)'
      }

      if (verticalFile && imgUrls?.vertical) {
        try {
          await uploadToPresignedUrl(imgUrls.vertical, verticalFile)
          uploadResults.vertical = 'uploaded'
        } catch (err) {
          uploadResults.vertical = `failed: ${err.message}`
        }
      } else if (!imgUrls?.vertical) {
        uploadResults.vertical = 'no url returned'
      } else {
        uploadResults.vertical = 'skipped (no file selected)'
      }

      setUploadStatus(uploadResults)
      setSubmitSuccess('Movie created successfully.')
      setFormData(initialMovieForm)
      setHorizontalFile(null)
      setVerticalFile(null)
      if (horizontalInputRef.current) horizontalInputRef.current.value = ''
      if (verticalInputRef.current) verticalInputRef.current.value = ''
    } catch (error) {
      setSubmitError(error.message || 'Unable to create movie.')
    } finally {
      setIsSubmitting(false)
    }
  }

  const inputClass = 'w-full rounded-md bg-black/30 border border-white/15 px-3 py-2 outline-none'

  return (
    <div className='space-y-6'>
      <Title text1='Add' text2='Movie' />

      <form onSubmit={handleSubmit} className='grid grid-cols-1 lg:grid-cols-2 gap-4'>
        <div className='space-y-2'>
          <label className='text-sm text-gray-300'>movie_id (optional)</label>
          <input
            value={formData.movie_id}
            onChange={(e) => handleChange('movie_id', e.target.value)}
            placeholder='Auto-generated by backend if empty'
            className={inputClass}
          />
        </div>

        <div className='space-y-2'>
          <label className='text-sm text-gray-300'>title *</label>
          <input
            value={formData.title}
            onChange={(e) => handleChange('title', e.target.value)}
            className={inputClass}
            required
          />
        </div>

        <div className='space-y-2 lg:col-span-2'>
          <label className='text-sm text-gray-300'>description *</label>
          <textarea
            value={formData.description}
            onChange={(e) => handleChange('description', e.target.value)}
            rows={4}
            className={inputClass}
            required
          />
        </div>

        <div className='space-y-2'>
          <label className='text-sm text-gray-300'>age_rating *</label>
          <select
            value={formData.age_rating}
            onChange={(e) => handleChange('age_rating', e.target.value)}
            className={inputClass}
            required
          >
            <option value=''>Select age rating</option>
            {ageRatingOptions.map((item) => (
              <option key={item} value={item}>{item}</option>
            ))}
          </select>
        </div>

        <div className='space-y-2'>
          <label className='text-sm text-gray-300'>release_date *</label>
          <input
            type='date'
            value={formData.release_date}
            onChange={(e) => handleChange('release_date', e.target.value)}
            className={inputClass}
            required
          />
        </div>

        <div className='space-y-2'>
          <label className='text-sm text-gray-300'>status *</label>
          <select
            value={formData.status}
            onChange={(e) => handleChange('status', e.target.value)}
            className={inputClass}
            required
          >
            <option value=''>Select status</option>
            {movieStatusOptions.map((item) => (
              <option key={item} value={item}>{item}</option>
            ))}
          </select>
        </div>

        <div className='space-y-2'>
          <label className='text-sm text-gray-300'>genre *</label>
          <select
            value={formData.genre}
            onChange={(e) => handleChange('genre', e.target.value)}
            className={inputClass}
            required
          >
            <option value=''>Select genre</option>
            {movieGenreOptions.map((item) => (
              <option key={item} value={item}>{item}</option>
            ))}
          </select>
        </div>

        <div className='space-y-2'>
          <label className='text-sm text-gray-300'>duration_minutes *</label>
          <input
            type='number'
            min='1'
            value={formData.duration_minutes}
            onChange={(e) => handleChange('duration_minutes', e.target.value)}
            className={inputClass}
            required
          />
        </div>

        <div className='space-y-2 lg:col-span-2'>
          <label className='text-sm text-gray-300'>trailerUrl *</label>
          <input
            value={formData.trailerUrl}
            onChange={(e) => handleChange('trailerUrl', e.target.value)}
            placeholder='https://www.youtube.com/watch?v=...'
            className={inputClass}
            required
          />
        </div>

        {/* Poster uploads — files are PUT to MinIO presigned URLs returned by backend */}
        <div className='space-y-2'>
          <label className='text-sm text-gray-300'>
            Horizontal poster <span className='text-gray-500'>(optional — auto-uploaded after creation)</span>
          </label>
          <input
            ref={horizontalInputRef}
            type='file'
            accept='image/*'
            onChange={(e) => setHorizontalFile(e.target.files?.[0] || null)}
            className='w-full text-sm text-gray-300 file:mr-3 file:py-1.5 file:px-3 file:rounded file:border-0 file:bg-primary/20 file:text-primary cursor-pointer'
          />
          {horizontalFile && (
            <p className='text-xs text-gray-400'>{horizontalFile.name}</p>
          )}
        </div>

        <div className='space-y-2'>
          <label className='text-sm text-gray-300'>
            Vertical poster <span className='text-gray-500'>(optional — auto-uploaded after creation)</span>
          </label>
          <input
            ref={verticalInputRef}
            type='file'
            accept='image/*'
            onChange={(e) => setVerticalFile(e.target.files?.[0] || null)}
            className='w-full text-sm text-gray-300 file:mr-3 file:py-1.5 file:px-3 file:rounded file:border-0 file:bg-primary/20 file:text-primary cursor-pointer'
          />
          {verticalFile && (
            <p className='text-xs text-gray-400'>{verticalFile.name}</p>
          )}
        </div>

        <div className='lg:col-span-2 space-y-2'>
          {submitError && (
            <p className='text-sm text-red-400'>{submitError}</p>
          )}

          {submitSuccess && (
            <p className='text-sm text-green-400'>{submitSuccess}</p>
          )}

          {(uploadStatus.horizontal || uploadStatus.vertical) && (
            <div className='text-xs space-y-1'>
              {uploadStatus.horizontal && (
                <p className={uploadStatus.horizontal === 'uploaded' ? 'text-green-400' : 'text-yellow-400'}>
                  Horizontal poster: {uploadStatus.horizontal}
                </p>
              )}
              {uploadStatus.vertical && (
                <p className={uploadStatus.vertical === 'uploaded' ? 'text-green-400' : 'text-yellow-400'}>
                  Vertical poster: {uploadStatus.vertical}
                </p>
              )}
            </div>
          )}

          <button
            type='submit'
            disabled={!canSubmit || isSubmitting}
            className='cursor-pointer px-4 py-2 rounded-md bg-primary text-black font-medium hover:opacity-90 transition-opacity duration-200 disabled:opacity-50 disabled:cursor-not-allowed'
          >
            {isSubmitting ? 'Creating movie...' : 'Create Movie'}
          </button>
        </div>
      </form>
    </div>
  )
}

export default AddMovie
