import React, { useMemo, useState } from 'react'
import Title from '../../components/admin/Title'
import { useAuth } from '../../context/AuthContext'
import { createMovie } from '../../lib/movieApi'

const ageRatingOptions = ['G', 'PG', 'PG13', 'R', 'NC17']
const movieStatusOptions = ['COMING_SOON', 'NOW_SHOWING', 'ENDED']
const movieGenreOptions = [
  'ACTION',
  'ADVENTURE',
  'ANIMATION',
  'COMEDY',
  'CRIME',
  'DRAMA',
  'FANTASY',
  'HORROR',
  'MYSTERY',
  'ROMANCE',
  'SCI_FI',
  'THRILLER',
]

const initialMovieForm = {
  movie_id: '',
  title: '',
  description: '',
  age_rating: '',
  release_date: '',
  status: '',
  genre: '',
  duration_minutes: '',
  trailerUrl: '',
}

const AddMovie = () => {
  const { token } = useAuth()

  const [formData, setFormData] = useState(initialMovieForm)
  const [submittedMovie, setSubmittedMovie] = useState(null)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [submitError, setSubmitError] = useState('')
  const [submitSuccess, setSubmitSuccess] = useState('')

  const canSubmit = useMemo(() => {
    return (
      formData.title &&
      formData.description &&
      formData.age_rating &&
      formData.release_date &&
      formData.status &&
      formData.genre &&
      Number(formData.duration_minutes) > 0 &&
      formData.trailerUrl
    )
  }, [formData])

  const handleChange = (field, value) => {
    setFormData((prev) => ({ ...prev, [field]: value }))
  }

  const handleSubmit = async (event) => {
    event.preventDefault()

    if (!canSubmit || isSubmitting) return

    setSubmitError('')
    setSubmitSuccess('')
    setSubmittedMovie(null)

    try {
      setIsSubmitting(true)

      const payload = {
        ...(formData.movie_id ? { movie_id: formData.movie_id } : {}),
        title: formData.title,
        description: formData.description,
        age_rating: formData.age_rating,
        release_date: formData.release_date,
        status: formData.status,
        genre: formData.genre,
        duration_minutes: Number(formData.duration_minutes),
        trailerUrl: formData.trailerUrl,
      }

      const response = await createMovie(payload, token)

      setSubmittedMovie(response)
      setSubmitSuccess('Movie created successfully.')
      setFormData(initialMovieForm)
    } catch (error) {
      setSubmitError(error.message || 'Unable to create movie.')
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <div className='space-y-6'>
      <Title text1='Add' text2='Movie' />

      <div className='rounded-xl border border-primary/20 bg-primary/10 p-4 text-sm text-gray-300'>
        Create a new movie and submit it to backend API.
      </div>

      <form onSubmit={handleSubmit} className='grid grid-cols-1 lg:grid-cols-2 gap-4'>
        <div className='space-y-2'>
          <label className='text-sm text-gray-300'>movie_id (optional)</label>
          <input
            value={formData.movie_id}
            onChange={(e) => handleChange('movie_id', e.target.value)}
            placeholder='Auto-generated by backend if empty'
            className='w-full rounded-md bg-black/30 border border-white/15 px-3 py-2 outline-none'
          />
        </div>

        <div className='space-y-2'>
          <label className='text-sm text-gray-300'>title *</label>
          <input
            value={formData.title}
            onChange={(e) => handleChange('title', e.target.value)}
            className='w-full rounded-md bg-black/30 border border-white/15 px-3 py-2 outline-none'
            required
          />
        </div>

        <div className='space-y-2 lg:col-span-2'>
          <label className='text-sm text-gray-300'>description *</label>
          <textarea
            value={formData.description}
            onChange={(e) => handleChange('description', e.target.value)}
            rows={4}
            className='w-full rounded-md bg-black/30 border border-white/15 px-3 py-2 outline-none'
            required
          />
        </div>

        <div className='space-y-2'>
          <label className='text-sm text-gray-300'>age_rating *</label>
          <select
            value={formData.age_rating}
            onChange={(e) => handleChange('age_rating', e.target.value)}
            className='w-full rounded-md bg-black/30 border border-white/15 px-3 py-2 outline-none'
            required
          >
            <option value=''>Select age rating</option>
            {ageRatingOptions.map((item) => (
              <option key={item} value={item}>
                {item}
              </option>
            ))}
          </select>
        </div>

        <div className='space-y-2'>
          <label className='text-sm text-gray-300'>release_date *</label>
          <input
            type='date'
            value={formData.release_date}
            onChange={(e) => handleChange('release_date', e.target.value)}
            className='w-full rounded-md bg-black/30 border border-white/15 px-3 py-2 outline-none'
            required
          />
        </div>

        <div className='space-y-2'>
          <label className='text-sm text-gray-300'>status *</label>
          <select
            value={formData.status}
            onChange={(e) => handleChange('status', e.target.value)}
            className='w-full rounded-md bg-black/30 border border-white/15 px-3 py-2 outline-none'
            required
          >
            <option value=''>Select status</option>
            {movieStatusOptions.map((item) => (
              <option key={item} value={item}>
                {item}
              </option>
            ))}
          </select>
        </div>

        <div className='space-y-2'>
          <label className='text-sm text-gray-300'>genre *</label>
          <select
            value={formData.genre}
            onChange={(e) => handleChange('genre', e.target.value)}
            className='w-full rounded-md bg-black/30 border border-white/15 px-3 py-2 outline-none'
            required
          >
            <option value=''>Select genre</option>
            {movieGenreOptions.map((item) => (
              <option key={item} value={item}>
                {item}
              </option>
            ))}
          </select>
        </div>

        <div className='space-y-2'>
          <label className='text-sm text-gray-300'>duration_minutes *</label>
          <input
            type='number'
            min='1'
            value={formData.duration_minutes}
            onChange={(e) => handleChange('duration_minutes', e.target.value)}
            className='w-full rounded-md bg-black/30 border border-white/15 px-3 py-2 outline-none'
            required
          />
        </div>

        <div className='space-y-2 lg:col-span-2'>
          <label className='text-sm text-gray-300'>trailerUrl *</label>
          <input
            value={formData.trailerUrl}
            onChange={(e) => handleChange('trailerUrl', e.target.value)}
            placeholder='https://www.youtube.com/watch?v=...'
            className='w-full rounded-md bg-black/30 border border-white/15 px-3 py-2 outline-none'
            required
          />
        </div>

        <div className='lg:col-span-2 space-y-2'>
          {submitError && (
            <p className='text-sm text-red-400'>{submitError}</p>
          )}

          {submitSuccess && (
            <p className='text-sm text-green-400'>{submitSuccess}</p>
          )}

          <button
            type='submit'
            disabled={!canSubmit || isSubmitting}
            className='cursor-pointer px-4 py-2 rounded-md bg-primary text-black font-medium hover:opacity-90 transition-opacity duration-200 disabled:opacity-50 disabled:cursor-not-allowed'
          >
            {isSubmitting ? 'Creating movie...' : 'Create Movie'}
          </button>
        </div>
      </form>

      {submittedMovie && (
        <div className='rounded-xl border border-primary/20 bg-primary/10 p-4'>
          <p className='font-medium mb-3'>Backend response preview</p>
          <pre className='text-xs whitespace-pre-wrap break-all bg-black/30 p-3 rounded-md border border-white/10'>
            {JSON.stringify(submittedMovie, null, 2)}
          </pre>
        </div>
      )}
    </div>
  )
}

export default AddMovie