server:
  port: 1325

spring:
  application:
    name: CinemaBooking

  jpa:
    hibernate:
      ddl-auto: update  # Options: none, validate, update, create, create-drop
    show-sql: false      # Show SQL statements in logs
    properties:
      hibernate:
        format_sql: false  # Format SQL for readability
        dialect: org.hibernate.dialect.MySQLDialect

app:
    appDomain: ${APP_DOMAIN:localhost}
    database:
      url: ${DB_HOST:localhost}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}

    jwt:
      secret: ${JWT_SECRET:defaultSecretKey}
      expirationMs: ${JWT_EXPIRATION_MS:3600000} # 1 hour in milliseconds

    paySecret:
      clientId: ${PAYOS_CLIENT_ID}
      apiKey: ${PAYOS_API_KEY}
      checksumKey: ${PAYOS_CHECKSUM_KEY}

    minio:
      url: ${MINIO_URL}
      accessKey: ${MINIO_ACCESS_KEY}
      secretKey: ${MINIO_SECRET_KEY}
      bucket: ${MINIO_BUCKET}